data:
  grade:
    normal: '|普'
    exceptional: '|擴'
    elite: 【精】
  weight:
    light: 輕
    medium: 中
    heavy: 重
  tc:
    "87": ★
    "84": ☆
  socket:
    "3": ' ③'
    "4": ' ④'
    "5": ' ⑤'
    "6": ' ⑥'
  color:
    white: "ÿc0"
    red: "ÿc1"
    green: "ÿc2"
    blue: "ÿc3"
    gray: "ÿc5"
    orange: "ÿc8"
    yellow: "ÿc9"
    pink: "ÿc;"
    dark_red: "ÿcS"

patches:
  - patches/01_runes_sound
  - patches/02_runes_texture
  - patches/03_key_texture
  - patches/04_light_pillar
  - patches/05_entrance_light
  - patches/06_highlight_cain
  - patches/07_layout
  - patches/09_better_arrow
  - patches/10_global_light
  - patches/11_level_names
  - patches/12_levelgroup_res

pipelines:
  - name: add English name (uniq/set items)
    resource: resources/generated/uniq-set.tsv
    template: |-
      {{ .enUS }}
      {{ .zhTW }}

  - name: add English name (set)
    resource: resources/generated/sets.tsv
    template: |-
      {{ .enUS }}
      {{ .zhTW }}

  - name: add English name (runes)
    resource: resources/generated/runes.tsv
    template: |-
      {{ .zhTW }} {{ .enName }}

  - name: add English name (runewords)
    resource: resources/generated/runewords.tsv
    template: |-
      {{ .enUS }}
      {{ .zhTW }}

  - name: add English name (skills)
    resource: resources/generated/skills.tsv
    template: |-
      {{ .enUS }}
      {{ .zhTW }}

  - name: add equip info
    resource: resources/generated/equip.tsv
    template: |-
      {{ .zhTW -}}
      {{- index .data.grade .grade }}
      {{- index .data.weight .weight }}
      {{- with .speed -}} 〔 {{- . -}} 〕 {{- end }}
      {{- if .max }}
        {{- if .grade | eq "elite" }}
          {{- if contains .type "tors|ashd" -}}
            ( {{- .max }}-e{{ .maxEth -}} )
          {{- else if ((contains .type "helm|circ") | and (.socket | eq "3")) | or ((contains .type "shie") | and (.socket | eq "4")) -}}
            ( {{- .max -}} )
          {{- end }}
        {{- else if .Key | eq "xtp" -}}
          ( {{- .max -}} )
        {{- end }}
      {{- end }}
      {{- index .data.tc .tc }}
      {{- index .data.socket .socket }}

  - name: staff mods
    resource: resources/generated/staff-mods.tsv
    template: |-
      {{ .zhTW -}} *

  - name: add MAX
    resource: resources/item_max.tsv
    lookup_string_files:
      - origin/data/local/lng/strings/skills.json
    template: |-
      [{{ lookupString .max }}]
      {{ .zhTW }}

  - name: modify gems
    resource: resources/generated/gems.tsv
    template: |-
      {{- if .inRune | and (lt (int .inRune) 20) -}}
        ÿc5[+ {{- .qty -}} x# {{- .inRune -}} =# {{- .outRune -}} ]
      {{ end -}}
      {{- if contains .rank "45" -}}
        ÿc1★ {{- .zhTW -}} ★
      {{- else -}}
        ÿcS {{- .zhTW -}}
      {{- end -}}
      ÿc0

  - name: modify item
    resource: resources/item_modify.tsv
    template: &modify |-
      {{- with .color }}{{ index $.data.color . }}{{ end }}
      {{- .prefix }}
      {{- if .newName | eq "(null)" }}
      {{- else if .newName }}
        {{- .newName }}
      {{- else }}
        {{- .zhTW }}
      {{- end }}
      {{- .suffix }}
      {{- with .color }}{{ index $.data.color "white" }}{{ end }}

  - name: modify runes
    resource: resources/generated/runes.tsv
    template: |-
      {{- $num := atoi .num }}
      {{- if .category | eq "in socket" }}
        {{- .zhTW }}#{{ printf "%02d" $num }}
      {{- else }}
        {{- if .recipeGem -}}
          {{- .data.color.gray -}}
          [x{{ .recipeQty -}} + {{- .recipeGem }}]
          {{- "\n" }}
          {{- .data.color.orange }}
        {{- end }}
        {{- .zhTW }}#{{ printf "%02d" $num }}
      {{- end }}

  - name: add map levels
    resource: resources/generated/levels.tsv
    template: |-
      {{ .zhTW }} [{{ .normal }}|{{ .nightmare }}|{{ .hell }}]

  - name: add level group res
    resource: resources/generated/levelgroup.tsv
    template: |-
      {{ .zhTW }} ÿc5(免疫:
      {{- if or (ge (atoi .maxFR) 100) (ge (atoi .maxLR) 100) (ge (atoi .maxCR) 100) (ge (atoi .maxPR) 100) (ge (atoi .maxDR) 100) (ge (atoi .maxMR) 100) }}
        {{- if ge (atoi .maxFR) 100 -}} ÿc1火 {{- if ge (atoi .maxFR) 117 -}} * {{- end -}} {{- end -}}
        {{- if ge (atoi .maxLR) 100 -}} ÿc9電 {{- if ge (atoi .maxLR) 117 -}} * {{- end -}} {{- end -}}
        {{- if ge (atoi .maxCR) 100 -}} ÿc3冰 {{- if ge (atoi .maxCR) 117 -}} * {{- end -}} {{- end -}}
        {{- if ge (atoi .maxPR) 100 -}} ÿc2毒 {{- if ge (atoi .maxPR) 111 -}} * {{- end -}} {{- end -}}
        {{- if ge (atoi .maxDR) 100 -}} ÿc4物 {{- if ge (atoi .maxDR) 110 -}} * {{- end -}} {{- end -}}
        {{- if ge (atoi .maxMR) 100 -}} ÿc8魔* {{- end -}}
      {{- else -}}
        ÿc0無
      {{- end -}}
      ÿc5
      {{- if eq .demon_undead "1" -}} ,只有不死惡魔 {{- end -}}
      )

  - name: modify text
    resource: resources/text_modify.tsv
    template: *modify

  - name: modify abbr
    resource: resources/text_abbr.tsv
    template: |-
      {{ mkAbbr .zhTW .abbr }}

