data:
  grade:
    normal: 普
    exceptional: 擴
    elite: 精
  weight:
    light: 輕
    medium: 中
    heavy: 重
  tc:
    "87": ★
    "84": ☆
  socket:
    "3": ' ③'
    "4": ' ④'
    "5": ' ⑤'
    "6": ' ⑥'
  color:
    white: "ÿc0"
    red: "ÿc1"
    green: "ÿc2"
    blue: "ÿc3"
    gray: "ÿc5"
    orange: "ÿc8"
    yellow: "ÿc9"
    pink: "ÿc;"
    dark-red: "ÿcS"

patches:
  - patches/01_runes_sound
  - patches/02_runes_texture
  - patches/03_key_texture
  - patches/04_light_pillar
  - patches/05_entrance_light
  - patches/06_highlight_cain
  - patches/07_layout
  - patches/09_better_arrow

pipelines:
  - name: add equip info
    resource: resources/generated/equip.tsv
    template: |-
      {{ .zhTW -}} |
      {{- index .data.grade .grade }}
      {{- index .data.weight .weight }}
      {{- with .speed -}} 〔 {{- . -}} 〕 {{- end }}
      {{- if .grade | eq "elite" | and .max | and (contains .type "tors|ashd") -}}
        ( {{- .max }}-e{{ .maxEth -}} )
      {{- end }}
      {{- index .data.tc .tc }}
      {{- index .data.socket .socket }}

  - name: add uniq-set info
    resource: resources/generated/uniq-set.tsv
    template: |-
      {{ .zhTW -}} ({{ .qlvl }})

  - name: add MAX
    resource: resources/item_max.tsv
    lookup_string_files:
      - origin/data/local/lng/strings/skills.json
    template: |-
      [{{ lookupString .max }}]
      {{ .zhTW }}

  - name: modify item
    resource: resources/item_modify.tsv
    template: &modify |-
      {{- with .color }}{{ index $.data.color . }}{{ end }}
      {{- .prefix }}
      {{- if .newName | eq "(null)" }}
      {{- else if .newName }}
        {{- .newName }}
      {{- else }}
        {{- .zhTW }}
      {{- end }}
      {{- .suffix }}
      {{- with .color }}{{ index $.data.color "white" }}{{ end }}

  - name: modify runes
    resource: resources/generated/runes.tsv
    template: |-
      {{- $num := atoi .num }}
      {{- if .category | eq "in socket" }}
        {{- .zhTW }}#{{ printf "%02d" $num }}
      {{- else }}
        {{- if .recipeGem -}}
          {{- .data.color.gray -}}
          [x{{ .recipeQty -}} + {{- .recipeGem }}]
          {{- "\n" }}
          {{- .data.color.orange }}
        {{- end }}
        {{- .zhTW }}#{{ printf "%02d" $num }}
      {{- end }}

  - name: add map levels
    resource: resources/generated/levels.tsv
    template: |-
      {{ .zhTW }} [{{ .normal }}|{{ .nightmare }}|{{ .hell }}]

  - name: modify text
    resource: resources/text_modify.tsv
    template: *modify

  - name: modify abbr
    resource: resources/text_abbr.tsv
    template: |-
      {{ mkAbbr .zhTW .abbr }}

